[[main]]
  name = "文章"
  pageRef = "post"
  weight = 10

[[main]]
  name = "归档"
  pageRef = "archives"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 40
