baseURL = "https://wellorbetter.github.io"
languageCode = "zh-CN"
title = "wellorbetter's blog"
theme = "PaperMod"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
paginate = 10

[params]
  author = "wellorbetter"
  description = "随手记录"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowFullTextinRSS = true
  profileMode.enabled = true
  profileMode.title = "wellorbetter"
  profileMode.subtitle = "随手记录"
  profileMode.imageUrl = "/image/769455.jpg"
  profileMode.imageWidth = 120
  profileMode.imageHeight = 120

[menu]
  [[menu.main]]
    name = "文章"
    url = "/post/"
    weight = 1
  [[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
