baseURL = "https://wellorbetter.github.io"
languageCode = "zh-CN"
title = "wellorbetter's blog"
theme = "PaperMod"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
paginate = 10

[params]
  author = "wellorbetter"
  description = "随手记录"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  ShowFullTextinRSS = true

  [params.profileMode]
    enabled = true
    title = "wellorbetter"
    subtitle = "努力学习魔法，希望有一天会收到霍格沃兹的录取通知书 = ="
    imageUrl = "/image/1061286.jpg"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "wellorbetter"

    [[params.profileMode.buttons]]
      name = "文章"
      url = "/post/"

    [[params.profileMode.buttons]]
      name = "归档"
      url = "/archives/"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/wellorbetter"

[[params.socialIcons]]
  name = "email"
  url = "mailto:1419919418@qq.com"

[menu]
  [[menu.main]]
    name = "文章"
    url = "/post/"
    weight = 1
  [[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
