backend:
  name: github
  repo: wellorbetter/wellorbetter.github.io
  branch: hugo

media_folder: static/images
public_folder: /images

collections:
  - name: posts
    label: 文章
    folder: content/post
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 发布时间, name: date, widget: datetime, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: 草稿, name: draft, widget: boolean, default: false }
      - { label: 标签, name: tags, widget: list, required: false }
      - { label: 分类, name: categories, widget: list, required: false }
      - { label: 正文, name: body, widget: markdown }
